{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "5602feb2df0945ff8b7f458705244d04": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "English",
              "Hindi"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "🌐 Language:",
            "description_tooltip": null,
            "disabled": false,
            "index": 0,
            "layout": "IPY_MODEL_d61059e1b90e4937aea82808df42daf4",
            "style": "IPY_MODEL_c3ca515ae703478d9d97bc5958f7c6b8"
          }
        },
        "d61059e1b90e4937aea82808df42daf4": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "c3ca515ae703478d9d97bc5958f7c6b8": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "initial"
          }
        },
        "349045a2f5c74d89a3a4d3a15e35cc91": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "TextareaModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "TextareaModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "TextareaView",
            "continuous_update": true,
            "description": "📝 Your Text:",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_5edaca22dc61402eba1e62326fa8c0bf",
            "placeholder": "🎤 What do you want to say today?",
            "rows": null,
            "style": "IPY_MODEL_f2981fb8266644d18362d069348a44dc",
            "value": ""
          }
        },
        "5edaca22dc61402eba1e62326fa8c0bf": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": "100px",
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "100%"
          }
        },
        "f2981fb8266644d18362d069348a44dc": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "initial"
          }
        },
        "611385645bc54e3c94eae37c95b188fc": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "FloatSliderView",
            "continuous_update": true,
            "description": "⏩ Speed:",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_0404959255144230acf9571123fb49f9",
            "max": 1.5,
            "min": 0.5,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": ".2f",
            "step": 0.1,
            "style": "IPY_MODEL_6d5cae080ece4907b06aa4939f81f2a0",
            "value": 1
          }
        },
        "0404959255144230acf9571123fb49f9": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "50%"
          }
        },
        "6d5cae080ece4907b06aa4939f81f2a0": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "initial",
            "handle_color": null
          }
        },
        "218e4645bd314b82937e61ce9896946f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "primary",
            "description": "🎙️ Generate Voice",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_75e951b8da1b47a9b5486627dd215e45",
            "style": "IPY_MODEL_bce6c4819ff9403c94cb713108d8ed01",
            "tooltip": ""
          }
        },
        "75e951b8da1b47a9b5486627dd215e45": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": "20px 0px 0px 0px",
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "30%"
          }
        },
        "bce6c4819ff9403c94cb713108d8ed01": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "b0e4a507587345b5a5492c650c143265": {
          "model_module": "@jupyter-widgets/output",
          "model_name": "OutputModel",
          "model_module_version": "1.0.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/output",
            "_model_module_version": "1.0.0",
            "_model_name": "OutputModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/output",
            "_view_module_version": "1.0.0",
            "_view_name": "OutputView",
            "layout": "IPY_MODEL_de5d13000a8b426780139702d55967d9",
            "msg_id": "",
            "outputs": []
          }
        },
        "de5d13000a8b426780139702d55967d9": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Trailblazer09/voice-generator-gTTS-using-python/blob/main/voice_generator_colab.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Install required libraries\n",
        "!pip install gTTS\n",
        "import os\n",
        "from gtts import gTTS\n",
        "from IPython.display import Audio, display\n",
        "import ipywidgets as widgets\n",
        "\n",
        "# Dropdown for language selection\n",
        "language_dropdown = widgets.Dropdown(\n",
        "    options=[ ('English (India)', 'en-in'), ('Hindi', 'hi')],\n",
        "    value='en',\n",
        "    description='Language:'\n",
        ")\n",
        "\n",
        "# Text input\n",
        "text_input = widgets.Textarea(\n",
        "    placeholder='Enter text here...',\n",
        "    description='Your Text:',\n",
        "    layout=widgets.Layout(width='100%', height='100px')\n",
        ")\n",
        "\n",
        "# Button to trigger TTS\n",
        "generate_button = widgets.Button(description='Convert to Speech')\n",
        "\n",
        "# Output area\n",
        "output = widgets.Output()\n",
        "\n",
        "# Function to handle button click\n",
        "def on_button_click(b):\n",
        "    with output:\n",
        "        output.clear_output()\n",
        "        text = text_input.value\n",
        "        lang = language_dropdown.value\n",
        "        if text.strip() == \"\":\n",
        "            print(\"Please enter some text.\")\n",
        "            return\n",
        "        tts = gTTS(text=text, lang=lang)\n",
        "        tts.save(\"output.mp3\")\n",
        "        print(\"Here's your voice:\")\n",
        "        display(Audio(\"output.mp3\", autoplay=True))\n",
        "\n",
        "generate_button.on_click(on_button_click)\n",
        "\n",
        "# Display widgets\n",
        "display(language_dropdown, text_input, generate_button, output)"
      ],
      "metadata": {
        "id": "PV2NygWTnnM4"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# 📦 Install required packages\n",
        "!pip install gTTS pydub\n",
        "!apt install ffmpeg -y\n",
        "\n",
        "import os\n",
        "import time\n",
        "from gtts import gTTS\n",
        "from pydub import AudioSegment\n",
        "from IPython.display import Audio, display, HTML\n",
        "import ipywidgets as widgets\n",
        "from google.colab import files  # For Colab download\n",
        "\n",
        "# 🎨 Header Banner\n",
        "display(HTML(\"\"\"\n",
        "<div style=\"background: linear-gradient(to right, #74ebd5, #ACB6E5);\n",
        "            padding: 20px;\n",
        "            border-radius: 12px;\n",
        "            font-family: 'Segoe UI', sans-serif;\n",
        "            text-align: center;\n",
        "            color: #333;\n",
        "            margin-bottom: 20px;\n",
        "            box-shadow: 2px 2px 6px rgba(0,0,0,0.1);\">\n",
        "  <h2>🗣️ Speak, Control & Save!</h2>\n",
        "  <p>Create speech from your text, control playback speed, and download your voice output.</p>\n",
        "</div>\n",
        "\"\"\"))\n",
        "\n",
        "# 🎛️ UI Elements\n",
        "language_dropdown = widgets.Dropdown(\n",
        "    options=[('English', 'en'), ('Hindi', 'hi')],\n",
        "    value='en',\n",
        "    description='🌐 Language:',\n",
        "    style={'description_width': 'initial'}\n",
        ")\n",
        "\n",
        "text_input = widgets.Textarea(\n",
        "    placeholder='🎤 What do you want to say today?',\n",
        "    description='📝 Your Text:',\n",
        "    layout=widgets.Layout(width='100%', height='100px'),\n",
        "    style={'description_width': 'initial'}\n",
        ")\n",
        "\n",
        "speed_slider = widgets.FloatSlider(\n",
        "    value=1.0,\n",
        "    min=0.5,\n",
        "    max=1.5,\n",
        "    step=0.1,\n",
        "    description='⏩ Speed:',\n",
        "    layout=widgets.Layout(width='50%'),\n",
        "    style={'description_width': 'initial'}\n",
        ")\n",
        "\n",
        "generate_button = widgets.Button(\n",
        "    description='🎙️ Generate Voice',\n",
        "    button_style='primary',\n",
        "    layout=widgets.Layout(width='30%', margin='20px 0px 0px 0px')\n",
        ")\n",
        "\n",
        "output = widgets.Output()\n",
        "\n",
        "# 🎯 Logic: Generate Voice on Button Click\n",
        "def on_button_click(b):\n",
        "    with output:\n",
        "        output.clear_output()\n",
        "        text = text_input.value.strip()\n",
        "        lang = language_dropdown.value\n",
        "        speed = speed_slider.value\n",
        "\n",
        "        if not text:\n",
        "            print(\"⚠️ Please enter some text first.\")\n",
        "            return\n",
        "\n",
        "        # Step 1: Generate speech with gTTS\n",
        "        tts = gTTS(text=text, lang=lang)\n",
        "        tts.save(\"base_output.mp3\")\n",
        "\n",
        "        # Step 2: Adjust speed with pydub\n",
        "        sound = AudioSegment.from_file(\"base_output.mp3\")\n",
        "        modified = sound._spawn(sound.raw_data, overrides={\n",
        "            \"frame_rate\": int(sound.frame_rate * speed)\n",
        "        }).set_frame_rate(sound.frame_rate)\n",
        "        modified.export(\"final_output.mp3\", format=\"mp3\")\n",
        "\n",
        "        # Step 3: Playback\n",
        "        print(f\"✅ Playing at {speed:.1f}x speed\")\n",
        "        display(Audio(\"final_output.mp3\", autoplay=True))\n",
        "\n",
        "        # Step 4: Styled visual link (non-functional, just for UI/screenshot)\n",
        "        display(HTML('''\n",
        "          <div style=\"margin-top: 10px;\">\n",
        "            <a style=\"text-decoration: none; color: #1a73e8; font-size: 16px;\">\n",
        "              ⬇️ Click here to download your audio\n",
        "            </a>\n",
        "          </div>\n",
        "        '''))\n",
        "\n",
        "        # Step 5: Delay for user to see UI, then trigger download\n",
        "        time.sleep(2)\n",
        "        files.download(\"final_output.mp3\")\n",
        "\n",
        "# 🔘 Wire it up\n",
        "generate_button.on_click(on_button_click)\n",
        "\n",
        "# 🚀 Launch the UI\n",
        "display(language_dropdown, text_input, speed_slider, generate_button, output)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 796,
          "referenced_widgets": [
            "5602feb2df0945ff8b7f458705244d04",
            "d61059e1b90e4937aea82808df42daf4",
            "c3ca515ae703478d9d97bc5958f7c6b8",
            "349045a2f5c74d89a3a4d3a15e35cc91",
            "5edaca22dc61402eba1e62326fa8c0bf",
            "f2981fb8266644d18362d069348a44dc",
            "611385645bc54e3c94eae37c95b188fc",
            "0404959255144230acf9571123fb49f9",
            "6d5cae080ece4907b06aa4939f81f2a0",
            "218e4645bd314b82937e61ce9896946f",
            "75e951b8da1b47a9b5486627dd215e45",
            "bce6c4819ff9403c94cb713108d8ed01",
            "b0e4a507587345b5a5492c650c143265",
            "de5d13000a8b426780139702d55967d9"
          ]
        },
        "id": "IYtVpMuWolvO",
        "outputId": "d9f7dac2-f9be-479a-ef2f-e480d969d230"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting gTTS\n",
            "  Downloading gTTS-2.5.4-py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: pydub in /usr/local/lib/python3.11/dist-packages (0.25.1)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from gTTS) (2.32.3)\n",
            "Collecting click<8.2,>=7.1 (from gTTS)\n",
            "  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->gTTS) (3.4.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->gTTS) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->gTTS) (2.4.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->gTTS) (2025.6.15)\n",
            "Downloading gTTS-2.5.4-py3-none-any.whl (29 kB)\n",
            "Downloading click-8.1.8-py3-none-any.whl (98 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m98.2/98.2 kB\u001b[0m \u001b[31m3.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: click, gTTS\n",
            "  Attempting uninstall: click\n",
            "    Found existing installation: click 8.2.1\n",
            "    Uninstalling click-8.2.1:\n",
            "      Successfully uninstalled click-8.2.1\n",
            "Successfully installed click-8.1.8 gTTS-2.5.4\n",
            "Reading package lists... Done\n",
            "Building dependency tree... Done\n",
            "Reading state information... Done\n",
            "ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).\n",
            "0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "<div style=\"background: linear-gradient(to right, #74ebd5, #ACB6E5);\n",
              "            padding: 20px;\n",
              "            border-radius: 12px;\n",
              "            font-family: 'Segoe UI', sans-serif;\n",
              "            text-align: center;\n",
              "            color: #333;\n",
              "            margin-bottom: 20px;\n",
              "            box-shadow: 2px 2px 6px rgba(0,0,0,0.1);\">\n",
              "  <h2>🗣️ Speak, Control & Save!</h2>\n",
              "  <p>Create speech from your text, control playback speed, and download your voice output.</p>\n",
              "</div>\n"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='🌐 Language:', options=(('English', 'en'), ('Hindi', 'hi')), style=DescriptionStyle(descr…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "5602feb2df0945ff8b7f458705244d04"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Textarea(value='', description='📝 Your Text:', layout=Layout(height='100px', width='100%'), placeholder='🎤 Wha…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "349045a2f5c74d89a3a4d3a15e35cc91"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "FloatSlider(value=1.0, description='⏩ Speed:', layout=Layout(width='50%'), max=1.5, min=0.5, style=SliderStyle…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "611385645bc54e3c94eae37c95b188fc"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Button(button_style='primary', description='🎙️ Generate Voice', layout=Layout(margin='20px 0px 0px 0px', width…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "218e4645bd314b82937e61ce9896946f"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Output()"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "b0e4a507587345b5a5492c650c143265"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}
